# Generated by Django 3.1.6 on 2021-02-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('coordinate_y', models.FloatField(null=True)),
                ('coordinate_x', models.FloatField(null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
