# Generated by Django 3.1.6 on 2021-02-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='coordinate_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='coordinate_y',
            field=models.FloatField(null=True),
        ),
    ]
